### ISSUE TITLE
weex create 报错

### ISSUE THREAD

**Issue by wqjGitHub** [weexteam/weex-toolkit#510]
weex 2.0.0-beta.4 创建项目：weex create e 错误
TypeError: Cannot read property 'error' of null
    at Cli.<anonymous> (/Users/*/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.4@@weex-cli/core/src/cli/cli.ts:188:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/*/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.4@@weex-cli/core/lib/cli/cli.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by erha19** [comment]
@wqjGitHub try `weex repair @weex-cli/generator`, then try it again. If it doesn't work, run `weex -v` to show your cli version to me.

**Comment by erha19** [comment]
@wqjGitHub also you can upgrade your `weex-toolkit` version by `npm i weex-toolkit@beta -g`, the latest version can handler this error correctly.
